/*
  C-file generated by Bin2C
  Compiled:    Dec 18 2024 at 15:24:24

  Copyright (C) 2018
  Segger Microcontroller GmbH
  www.segger.com

  The Embedded Experts
*/

static const unsigned char _acexample[12UL + 1] = {
  0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01, 0x02, 0x03, 0xFF, 0xFE, 0xFD, 0xFC, 0x00
};

/*************************** End of file ****************************/
